version: '3.4'

services:
  site:
    networks:
      - internal
      - web
    environment: 
      DATABASE_URL: 'postgresql://postgres:postgres@db:5432/postgres?schema=public'
    depends_on:
      - db
    env_file: .env
    build:
      args:
        - NEXT_PUBLIC_GOOGLE_CLIENT_ID=${NEXT_PUBLIC_GOOGLE_CLIENT_ID}
        - NEXT_PUBLIC_DISCORD_INVITE=${NEXT_PUBLIC_DISCORD_INVITE}
      context: .
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.website.tls.certresolver=default"
  
  db:
    image: postgres:13
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - internal
    environment: 
      POSTGRES_PASSWORD: 'postgres'

networks:
  internal:
  web:
    external: true
