version: '3.4'

services:
  site:
    image: kube/website:v1
    networks:
      - internal
      - web
    environment: 
      DATABASE_URL: 'postgresql://postgres:postgres@db:5432/postgres?schema=public'
    depends_on:
      - db
    build:
      context: .
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.website.tls.certresolver=default"
  
  db:
    image: postgres
    networks:
      - internal
    environment: 
      POSTGRES_PASSWORD: 'postgres'

networks:
  internal:
  web:
    external: true
