name: Deploy after checks have passed
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Wait on tests
        uses: lewagon/wait-on-check-action@v0.1
        with:
          ref: main
          check-name: build
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 20 # seconds
      - name: Deploy
        uses: sagebind/docker-swarm-deploy-action@v2
        with:
          remote_host: ssh://kube@kubemtu.com
          ssh_private_key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
          ssh_public_key: ${{ secrets.DOCKER_SSH_PUBLIC_KEY }}
          args: stack deploy --compose-file app.yml website
