name: Deploy after checks have passed
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Wait on tests
        uses: lewagon/wait-on-check-action@master
        with:
          ref: ${{ github.sha }}
          check-name: build
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10 # seconds
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: kubemtu.com
          username: kube
          key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
          script: |
            cd /docker/website
            git pull
            docker-compose build
            ./deployment.sh
