name: Deploy after checks have passed
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Wait on tests
        uses: lewagon/wait-on-check-action@v0.1
        with:
          ref: main
          check-name: build
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 20 # seconds
      - name: Deploy
        uses: wshihadeh/docker-deployment-action@v1
        with:
          remote_docker_host: kube@kubemtu.com
          ssh_private_key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
          ssh_public_key: ${{ secrets.DOCKER_SSH_PUBLIC_KEY }}
          deployment_mode: docker-swarm
          stack_file_name: app.yml
          args: website
